name: Build Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: List files in build/libs
        run: |
          echo "Checking contents of build/libs:"
          ls -l build/libs || echo "Directory does not exist or is empty"

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: invisibility_particles_mod
          path: build/libs/


