name: Build Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

- name: Список файлов после сборки
  run: |
    echo "Содержимое папки build/libs:"
    ls -l build/libs || echo "Папка отсутствует или пуста"

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: invisibility_particles_mod
          path: build/libs/
